### ISSUE TITLE
Error when running benchmark

### ISSUE THREAD

**Issue by klanderson** [kwgoodman/bottleneck#190]
```
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import bottleneck as bn
>>> bn.bench()
Bottleneck performance benchmark
    Bottleneck 1.2.1; Numpy 1.14.2
    Speed is NumPy time divided by Bottleneck time
    NaN means approx one-fifth NaNs; float64 used

              no NaN     no NaN      NaN       no NaN      NaN
               (100,)  (1000,1000)(1000,1000)(1000,1000)(1000,1000)
               axis=0     axis=0     axis=0     axis=1     axis=1
nansum         18.8        0.7        2.0        0.8        2.4
nanmean        84.1        1.3        1.6        2.5        2.6
nanstd        128.3        1.3        1.6        2.0        2.4
nanvar        123.5        1.3        1.6        2.0        2.4
nanmin         15.6        0.5        0.5        1.1        1.1
nanmax         15.8        0.5        0.5        1.1        1.1
median         98.0        1.2        5.5        1.1        6.6
nanmedian      93.9        4.9        5.8        5.0        5.6
ss              9.7        0.9        0.9        1.0        1.1
nanargmin      45.7        2.4        3.7        2.6        4.8
nanargmax      44.9        2.3        3.9        2.4        4.9
anynan          8.6        0.3       51.5        0.7       42.3
allnan         12.0      178.6      150.0      110.4      102.6
rankdata       42.3        1.2        1.2        2.1        2.1
nanrankdata    46.2        1.4        1.3        2.4        2.3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxxx/anaconda/envs/lsl-base/lib/python3.6/site-packages/bottleneck/benchmark/bench.py", line 77, in bench
    speed = timer(test['statements'], test['setups'])
  File "/Users/xxxx/anaconda/envs/lsl-base/lib/python3.6/site-packages/bottleneck/benchmark/bench.py", line 87, in timer
    t0 = autotimeit(statements[0], setup)
  File "/Users/xxxx/anaconda/envs/lsl-base/lib/python3.6/site-packages/bottleneck/benchmark/autotimeit.py", line 7, in autotimeit
    number, time1 = autoscaler(timer, mintime)
  File "/Users/xxxx/anaconda/envs/lsl-base/lib/python3.6/site-packages/bottleneck/benchmark/autotimeit.py", line 15, in autoscaler
    time = timer.timeit(number)
  File "/Users/xxxx/anaconda/envs/lsl-base/lib/python3.6/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 16, in inner
TypeError: `n` must be an integer
```

**Comment by kwgoodman** [comment]
I can't reproduce. Can you do some debugging and see what type `n` is if it is not an integer?

Might be good to look at `number` as well in
```
File "/Users/xxxx/anaconda/envs/lsl-base/lib/python3.6/site-packages/bottleneck/benchmark/autotimeit.py", line 15, in autoscaler
    time = timer.timeit(number)
```

**Comment by klanderson** [comment]
`number` is an int and equals 1 right before the crash.

These are the arguments (`statements[0]` and `setup`) being sent to autotimeit on bench.py Line 87:
```
bn_func(a, n, axis)

from bottleneck.benchmark.bench import getarray
a = getarray((100,), 'float64', False, 'C')
axis=0

from bottleneck import partition as bn_func
from bottleneck.slow import partition as sl_func
if axis is None: n = a.size
else: n = a.shape[axis] - 1
n = max(n / 2, 0)
```

Maybe the `n` in `setup`, which is being passed to initialize a `timeit.Timer` [`autotimeit.py`, Line 6] is messing with an `n` inside of `timeit.Timer` used on the call to `timeit`

**Comment by kwgoodman** [comment]
Ack! The problem is
```
n = max(n / 2, 0)
```
which should be (for py3 compat):
```
n = max(n // 2, 0)
```
But that has already been fixed in master: https://github.com/kwgoodman/bottleneck/issues/175
