### ISSUE TITLE
Porting bottleneck to numpy 1.9

### ISSUE THREAD

**Issue by charris** [kwgoodman/bottleneck#88]
Just a heads up that nansum now returns 0 for empty slices.
```
======================================================================
FAIL: Test nansum.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python27-x64\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "X:\Python27-x64\lib\site-packages\bottleneck\tests\func_test.py", line 80, in unit_maker
    assert_array_equal(actual, desired, err_msg)
  File "D:\Build\Test\numpy-build\numpy\testing\utils.py", line 734, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "D:\Build\Test\numpy-build\numpy\testing\utils.py", line 623, in assert_array_compare
    chk_same_position(x_isnan, y_isnan, hasval='nan')
  File "D:\Build\Test\numpy-build\numpy\testing\utils.py", line 603, in chk_same_position
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

func nansum | input a24 (float32) | shape (0L,) | axis -1

Input array:
[]

x and y nan location mismatch:
 x: array(nan, dtype=float32)
 y: array(0.0, dtype=float32)
```

**Comment by kwgoodman** [comment]
The rewrite of bottleneck works with numpy 1.9.1.
